### ISSUE TITLE
Features checklist

### ISSUE THREAD

**Issue by brycefrank** [allometric/alloview#1]
- [ ] Tooltips for variables
- [ ] Expandable covariate ellipse
- [ ] Tag categories
- [ ] Tag autocomplete
- [ ] Expandable row or modal for model summary
- [ ] Links to publication modals?
